global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "service", "severity"]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 30m
  receiver: default-log

receivers:
  - name: default-log

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: ["alertname", "service"]
