global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: wiki-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["wiki-api:8081"]

  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:8888"]

  - job_name: tempo
    static_configs:
      - targets: ["tempo:3200"]
