global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/wiki-alert-rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: wiki-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["wiki-api:8081"]

  - job_name: tempo
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: mysqld-exporter
    static_configs:
      - targets: ["mysqld-exporter:9104"]

  - job_name: kafka-exporter
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: kafka-jmx-exporter
    static_configs:
      - targets: ["kafka-jmx-exporter:5556"]
